site_name: Teamstudio Usage 1.1

nav:
  - 'index.md'
  - 'installing.md'
  - 'configuration.md'
  - 'overview.md'
  - 'catalog.md'
  - 'usage.md'
  - 'export.md'
  - 'filters.md'
  - 'release.md'

theme:
  name: material
      
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  
plugins:
  - search
